/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class s_android_ffmpeg_FFmpegNative */

#ifndef _Included_s_android_ffmpeg_FFmpegNative
#define _Included_s_android_ffmpeg_FFmpegNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     s_android_ffmpeg_FFmpegNative
 * Method:    decoderInit
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_s_android_ffmpeg_FFmpegNative_decoderInit
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     s_android_ffmpeg_FFmpegNative
 * Method:    decodeData
 * Signature: ([BI[B)I
 */
JNIEXPORT jint JNICALL Java_s_android_ffmpeg_FFmpegNative_decodeData
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray);

/*
 * Class:     s_android_ffmpeg_FFmpegNative
 * Method:    releaseDecoder
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_s_android_ffmpeg_FFmpegNative_releaseDecoder
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
